### ISSUE TITLE
ANN/BNN paper remix for ALIFE ?

### ISSUE THREAD

**Issue by jesparent** [OREL-group/Saturday-Morning-NeuroSim#17]

**Comment by krishnakatyal** [comment]
Done...sent you the google doc link. :)

**Comment by jesparent** [comment]
@krishnakatyal  did you send it in slack? I forget where it is : |

**Comment by devoworm** [comment]
Don't think I have the link to this either. Put it in the Slack channel (DevoWorm).

**Comment by krishnakatyal** [comment]
https://docs.google.com/document/d/1OCrmbe22gocVneZRCWPf-QZmmWbO89s59rk56DbYayA/edit?usp=sharing


I have given edit access to you both @balicea @jesparent

**Comment by jesparent** [comment]
@krishnakatyal @Orthogonal-Research-Lab maybe we could have a slack discussion about this soon?

**Comment by jesparent** [comment]
oh - I see there's a new paper doc - nvm - will add there.

**Comment by jesparent** [comment]
@krishnakatyal  is this paper submitted / still being worked on? I'm going this issue now, but if this paper (this version, I think there are others) is still open, let me know / re  open it.
