### ISSUE TITLE
Revisit Note Taking discussion from NOV 14

### ISSUE THREAD

**Issue by jesparent** [OREL-group/Saturday-Morning-NeuroSim#3]
We had a significantly interesting and relevant discussion hat should be checked back on next week / continued in the future. 

- [x] ? Best timeline apps/software?

- [ ] Demo (Deploy) or Die  review

- [x] Tweets and Micro Blog

- [x] Mandatory arbitrary reference to Twirlybirds (Jesse)

- [ ] "twitter together" github app? https://github.com/marketplace/actions/twitter-together

**Comment by rishistyping** [comment]
References:
https://obsidian.md/
https://app.readcube.com/
