### ISSUE TITLE
Rebuttal/Revision for Shared Rep. Submission

### ISSUE THREAD

**Issue by Orthogonal-Research-Lab** [OREL-group/Saturday-Morning-NeuroSim#8]

**Comment by jesparent** [comment]
I'm not sure if this ever fully got converted into another paper like BabyMinds did? @Orthogonal-Research-Lab

**Comment by jesparent** [comment]
any updates on this? @Orthogonal-Research-Lab

**Comment by Orthogonal-Research-Lab** [comment]
No. Might do something this summer.
